export const vowels = [
    {pronounce: "A as in glass", display: "æ", code: 11100},
    {pronounce: "AR as in arm", display: "Â", code: 11011},
    {pronounce: "AH as in swan", display: "ɑ", code: 1100},
    {pronounce: "AY as in bay", display: "é", code: 1000},
    {pronounce: "E as in end", display: "ɛ", code: 111},
    {pronounce: "EE as in bee", display: "i", code: 1111},
    {pronounce: "EER as in beer", display: "Î", code: 1101},
    {pronounce: "EH as in the", display: "ə", code: 11000},
    {pronounce: "ERE as in air", display: "Ê", code: 101},
    {pronounce: "I as in bit", display: "I", code: 11},
    {pronounce: "IE as in guy", display: "á", code: 10000},
    {pronounce: "IR as in bird", display: "ɝ", code: 10111},
    {pronounce: "OH as in toe", display: "o", code: 11111},
    {pronounce: "OI as in toy", display: "ó", code: 10},
    {pronounce: "OO as in too", display: "ú", code: 11110},
    {pronounce: "OU as in wolf", display: "ʊ", code: 110},
    {pronounce: "OW as in how", display: "å", code: 1},
    {pronounce: "ORE as in your", display: "Ô", code: 11101},
    {pronounce: " ", display: "", code: 0},
]

export const consonants = [
    {pronounce: "B as in baby", display: "b", code: 10001},
    {pronounce: "CH as in chat", display: "c", code: 1010},
    {pronounce: "D as in dog", display: "d", code: 10101},
    {pronounce: "F as in fox", display: "f", code: 100110},
    {pronounce: "g as in gun", display: "g", code: 100011},
    {pronounce: "H as in hop", display: "h", code: 10011},
    {pronounce: "J as in jam", display: "ʤ", code: 10100},
    {pronounce: "K as in kart", display: "k", code: 110001},
    {pronounce: "L as in live", display: "l", code: 10010},
    {pronounce: "M as in man", display: "m", code: 101},
    {pronounce: "N as in Net", display: "n", code: 1101},
    {pronounce: "NG as in rink", display: "ŋ", code: 111111},
    {pronounce: "P as in poppy", display: "p", code: 100010},
    {pronounce: "R as in run", display: "r", code: 110010},
    {pronounce: "S as in sit", display: "s", code: 110110},
    {pronounce: "SH as in shut", display: "ʃ", code: 101111},
    {pronounce: "T as in tunic", display: "t", code: 101010},
    {pronounce: "TH as in thick", display: "θ", code: 111010},
    {pronounce: "TH as in this", display: "ð", code: 10111},
    {pronounce: "V as in vine", display: "v", code: 11001},
    {pronounce: "W as in wit", display: "w", code: 101000},
    {pronounce: "Y as in you", display: "j", code: 11010},
    {pronounce: "Z as in zip", display: "z", code: 11011},
    {pronounce: "ZH as in Azure", display: "ʒ", code: 111101},
    {pronounce: " ", display: "", code: 0},
]

export const combined = vowels.concat(consonants)
